project:
  type: website

website:
  title: "wsny.dev"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/
      - icon: github
        href: https://github.com
format:
  html:
    theme:
      - morph
      - brand
    css: styles.css



