project:
  type: website

website:
  title: "wsny.dev"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/wrsnyder
      - icon: github
        href: https://github.com/snyrw
format:
  html:
    theme:
      - morph
      - brand
    css: styles.css



